package cc.protea.spreedly.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Created by jason on 5/3/17.
 */

@XmlRootElement(name = "transaction")
@XmlAccessorType(XmlAccessType.FIELD)
public class SpreedlyGatewayRedactResponse {

    /**
     * A unique string generated by Spreedly to identify a transaction.
     */
    public String token;

    /**
     * true if transaction was successful.
     */
    public boolean succeeded;

    /**
     * true if gateway was redacted.
     */
    public boolean redacted;

    public SpreedlyMessage message;

    public SpreedlyGatewayAccount gateway;

    public SpreedlyGatewayAccountState state;

    /**
     * @return true if transaction was successful.
     */
    public boolean isSucceeded() {
        return succeeded;
    }
    /**
     * @param succeeded true if transaction was successful.
     */
    public SpreedlyGatewayRedactResponse setSucceeded(final boolean succeeded) {
        this.succeeded = succeeded;
        return this;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public SpreedlyMessage getMessage() {
        return message;
    }

    public void setMessage(SpreedlyMessage message) {
        this.message = message;
    }

    public boolean isRedacted() {
        return redacted;
    }

    public void setRedacted(boolean redacted) {
        this.redacted = redacted;
    }

    public SpreedlyGatewayAccount getGateway() {
        return gateway;
    }

    public void setGateway(SpreedlyGatewayAccount gateway) {
        this.gateway = gateway;
    }

    public SpreedlyGatewayAccountState getState() {
        return state;
    }

    public void setState(SpreedlyGatewayAccountState state) {
        this.state = state;
    }

}
