package cc.protea.spreedly.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

@XmlRootElement(name = "transaction")
@XmlAccessorType(XmlAccessType.FIELD)
public class SpreedlyTransactionRequest {
	/**
	 * A unique string generated by Spreedly to identify a gateway.
	 */
	@XmlTransient public String gatewayAccountToken;

	/**
	 * A unique string generated by Spreedly to identify a transaction.
	 */
	@XmlTransient public String referenceTransactionToken;

	/**
	 * Any positive whole number, for example 1234 = $12.34.
	 */
	@XmlElement(name = "amount") public Integer amountInCents;

	/**
	 * ISO 4217 Currency Code e.g., USD, MXN, EUR
	 */
	@XmlElement(name = "currency_code") public String currencyCode;

	/**
	 * A unique string generated by Spreedly to identify a payment method.
	 */
	@XmlElement(name = "payment_method_token") public String paymentMethodToken;

	/**
	 * Setting this value to true will make the payment method be saved permanently. Otherwise it will remain in the cached state for three minutes.
	 */
	@XmlElement(name = "retain_on_success") public boolean retainOnSuccess;

	/**
	 * A merchant specified tracking number.
	 */
	@XmlElement(name = "order_id") public String orderId;

	/**
	 * Description of product or service sold.
	 */
	public String description;

	/**
	 * Customer IP address.
	 */
	@XmlElement(name = "ip") public String clientIpAddress;

	/**
	 * Customer email address.
	 */
	public String email;

	/**
	 * Custom name description that may end up on bank statement, depending on the gateway.
	 */
	@XmlElement(name = "merchant_name_descriptor") public String merchantNameDescriptor;

	/**
	 * Custom location description that may end up on bank statement, depending on the gateway.
	 */
	@XmlElement(name = "merchant_location_descriptor") public String merchantLocationDescriptor;

	/**
	 * @return A unique string generated by Spreedly to identify a gateway.
	 */
	public String getGatewayAccountToken() {
		return gatewayAccountToken;
	}
	/**
	 * @param A unique string generated by Spreedly to identify a gateway.
	 */
	public SpreedlyTransactionRequest setGatewayAccountToken(final String gatewayAccountToken) {
		this.gatewayAccountToken = gatewayAccountToken;
		return this;
	}

	/**
	 * @return A unique string generated by Spreedly to identify a transaction.
	 */
	public String getReferenceTransactionToken() {
		return referenceTransactionToken;
	}
	/**
	 * @param referenceTransactionToken A unique string generated by Spreedly to identify a transaction.
	 */
	public SpreedlyTransactionRequest setReferenceTransactionToken(final String referenceTransactionToken) {
		this.referenceTransactionToken = referenceTransactionToken;
		return this;
	}

	/**
	 * @return Any positive whole number, for example 1234 = $12.34.
	 */
	public Integer getAmountInCents() {
		return amountInCents;
	}
	/**
	 * @param amountInCents Any positive whole number, for example 1234 = $12.34.
	 */
	public SpreedlyTransactionRequest setAmountInCents(final Integer amountInCents) {
		this.amountInCents = amountInCents;
		return this;
	}

	/**
	 * @return ISO 4217 Currency Code e.g., USD, MXN, EUR
	 */
	public String getCurrencyCode() {
		return currencyCode;
	}
	/**
	 * @param currencyCode ISO 4217 Currency Code e.g., USD, MXN, EUR
	 */
	public SpreedlyTransactionRequest setCurrencyCode(final String currencyCode) {
		this.currencyCode = currencyCode;
		return this;
	}

	/**
	 * @return A unique string generated by Spreedly to identify a payment method.
	 */
	public String getPaymentMethodToken() {
		return paymentMethodToken;
	}
	/**
	 * @param paymentMethodToken A unique string generated by Spreedly to identify a payment method.
	 */
	public SpreedlyTransactionRequest setPaymentMethodToken(final String paymentMethodToken) {
		this.paymentMethodToken = paymentMethodToken;
		return this;
	}

	/**
	 * @return True will make the payment method be saved permanently. Otherwise it will remain in the cached state for three minutes.
	 */
	public boolean isRetainOnSuccess() {
		return retainOnSuccess;
	}
	/**
	 * @param retainOnSuccess Setting this value to true will make the payment method be saved permanently. Otherwise it will remain in the cached state for three minutes.
	 */
	public SpreedlyTransactionRequest setRetainOnSuccess(final boolean retainOnSuccess) {
		this.retainOnSuccess = retainOnSuccess;
		return this;
	}

	/**
	 * @return A merchant specified tracking number.
	 */
	public String getOrderId() {
		return orderId;
	}
	/**
	 * @param orderId A merchant specified tracking number.
	 */
	public SpreedlyTransactionRequest setOrderId(final String orderId) {
		this.orderId = orderId;
		return this;
	}

	/**
	 * @return Description of product or service sold.
	 */
	public String getDescription() {
		return description;
	}
	/**
	 * @param description Description of product or service sold.
	 */
	public SpreedlyTransactionRequest setDescription(final String description) {
		this.description = description;
		return this;
	}

	/**
	 * @return Customer IP address.
	 */
	public String getClientIpAddress() {
		return clientIpAddress;
	}
	/**
	 * @param clientIpAddress Customer IP address.
	 */
	public SpreedlyTransactionRequest setClientIpAddress(final String clientIpAddress) {
		this.clientIpAddress = clientIpAddress;
		return this;
	}

	/**
	 * @return Customer email address.
	 */
	public String getEmail() {
		return email;
	}
	/**
	 * @param email Customer email address.
	 */
	public SpreedlyTransactionRequest setEmail(final String email) {
		this.email = email;
		return this;
	}

	/**
	 * @return Custom name description that may end up on bank statement, depending on the gateway.
	 */
	public String getMerchantNameDescriptor() {
		return merchantNameDescriptor;
	}
	/**
	 * @param merchantNameDescriptor Custom name description that may end up on bank statement, depending on the gateway.
	 */
	public SpreedlyTransactionRequest setMerchantNameDescriptor(final String merchantNameDescriptor) {
		this.merchantNameDescriptor = merchantNameDescriptor;
		return this;
	}

	/**
	 * @return Custom location description that may end up on bank statement, depending on the gateway.
	 */
	public String getMerchantLocationDescriptor() {
		return merchantLocationDescriptor;
	}
	/**
	 * @param merchantLocationDescriptor Custom location description that may end up on bank statement, depending on the gateway.
	 */
	public SpreedlyTransactionRequest setMerchantLocationDescriptor(final String merchantLocationDescriptor) {
		this.merchantLocationDescriptor = merchantLocationDescriptor;
		return this;
	}



}